### PR TITLE
Restored extras_require

### PR DESCRIPTION
**Pull request by jmichalicek**
* Restored extras_require to handle different dependencies for python 3.0+ vs 2.7

### CODE REVIEW

**Comment by tomviner** [comment]
+1. Tested and this branch is required for me to install with Django 1.10 and Python 2.

**Comment by bhrutledge** [comment]
👍  I'm happy to report that requiring `-e git+https://github.com/jmichalicek/dj-pagination.git@restore-extras-require#egg=dj-pagination
` leads to a successful `pip install` on Django 1.11.9 and Python 2.7.14.

Could this get merged and released? I'm preparing for a deployment of a Django upgrade.

**Comment by pydanny** [comment]
Released 2.3.2: https://pypi.python.org/pypi/dj-pagination

**Comment by jmichalicek** [comment]
Thanks @pydanny 

@bhrutledge @tomviner I've been running into this sort of thing on and off with various packages.  Not sure why I never mentioned it here, but another temporary workaround for this sort of issue is to install Django first.  I was typing this up right while it got released, so managed to get in an example before pypi updates.

```
(djpag) ➜  dj-pagination-test python --version
Python 2.7.13
(djpag) ➜  dj-pagination-test pip install 'django<2'
Collecting django<2
  Using cached Django-1.11.9-py2.py3-none-any.whl
Requirement already satisfied: pytz in /Users/justin/.pyenv/versions/2.7.13/envs/djpag/lib/python2.7/site-packages (from django<2)
Installing collected packages: django
Successfully installed django-1.11.9
(djpag) ➜  dj-pagination-test pip install dj-pagination
Requirement already satisfied: dj-pagination in /Users/justin/.pyenv/versions/2.7.13/envs/djpag/lib/python2.7/site-packages
Requirement already satisfied: Django<2.0,>=1.8; python_version < "3.0" in /Users/justin/.pyenv/versions/2.7.13/envs/djpag/lib/python2.7/site-packages (from dj-pagination)
Requirement already satisfied: pytz in /Users/justin/.pyenv/versions/2.7.13/envs/djpag/lib/python2.7/site-packages (from Django<2.0,>=1.8; python_version < "3.0"->dj-pagination)
```
I was also been mucking about with the `--no-deps` flag which I expected to solve it, but it still seems to check versions.

**Pull request merged**
